export type MenuItem = {
  id: number;
  name: string;
  price: number;
  category: string;
  isFamous?: boolean;
  type: 'veg' | 'non-veg' | 'egg';
};

export const MENU_ITEMS: MenuItem[] = [
  { id: 1, name: "Puri Sabji (4 pcs)", price: 30, category: "Breakfast", type: 'veg' },
  { id: 2, name: "4 Roti Sabji", price: 50, category: "Meal", type: 'veg' },
  { id: 3, name: "Bread Omelette", price: 35, category: "Breakfast", type: 'egg' },
  { id: 4, name: "Aloo Paratha", price: 20, category: "Breakfast", type: 'veg' },
  { id: 5, name: "Paneer Paratha (Amul Paneer)", price: 40, category: "Breakfast", type: 'veg' },
  { id: 6, name: "Sattu Paratha", price: 25, category: "Breakfast", type: 'veg' },
  { id: 7, name: "Chana Bhatura", price: 50, category: "Breakfast", type: 'veg' },
  { id: 8, name: "Bread Butter / Jam", price: 25, category: "Breakfast", type: 'veg' },
  { id: 9, name: "Boiled Egg (2 pcs)", price: 25, category: "Snacks", type: 'egg' },
  { id: 10, name: "Uttapam", price: 45, category: "South Indian", type: 'veg' },
  { id: 11, name: "Idli (2 pcs)", price: 40, category: "South Indian", type: 'veg' },
  { id: 12, name: "Masala Dosa", price: 60, category: "South Indian", type: 'veg' },
  { id: 13, name: "Plain Dosa", price: 50, category: "South Indian", type: 'veg' },
  { id: 14, name: "Plain Maggi", price: 25, category: "Snacks", type: 'veg' },
  { id: 15, name: "Veg Maggi", price: 35, category: "Snacks", type: 'veg' },
  { id: 16, name: "Egg Maggi", price: 45, category: "Snacks", type: 'egg' },
  { id: 17, name: "Veg Sandwich", price: 25, category: "Snacks", type: 'veg' },
  { id: 18, name: "Grilled Veg Sandwich", price: 30, category: "Snacks", type: 'veg' },
  { id: 19, name: "Veg Meal (Rice, Dal, Sabji)", price: 60, category: "Meal", type: 'veg' },
  { id: 20, name: "Egg Curry (2 pcs)", price: 40, category: "Main Course", type: 'egg' },
  { id: 21, name: "Chicken Curry (2 pcs)", price: 70, category: "Main Course", type: 'non-veg' },
  { id: 22, name: "Fish Curry (2 pcs)", price: 60, category: "Main Course", type: 'non-veg' },
  { id: 23, name: "Mutton Curry (2 pcs)", price: 150, category: "Main Course", isFamous: true, type: 'non-veg' },
  { id: 24, name: "Omelette (Double Egg)", price: 30, category: "Snacks", type: 'egg' },
  { id: 25, name: "Chicken Biryani", price: 80, category: "Biryani", isFamous: true, type: 'non-veg' },
  { id: 26, name: "Egg Biryani", price: 60, category: "Biryani", type: 'egg' },
  { id: 27, name: "Chicken Egg Biryani", price: 70, category: "Biryani", type: 'non-veg' },
  { id: 28, name: "Veg Biryani", price: 85, category: "Biryani", type: 'veg' },
  { id: 29, name: "Paneer Butter Masala (Amul Paneer)", price: 75, category: "Main Course", type: 'veg' },
  { id: 30, name: "Matar Paneer (Amul Paneer)", price: 50, category: "Main Course", type: 'veg' },
  { id: 31, name: "Palak Paneer (Amul Paneer)", price: 70, category: "Main Course", type: 'veg' },
  { id: 32, name: "Chana Masala", price: 50, category: "Main Course", type: 'veg' },
  { id: 33, name: "Aloo Jeera", price: 50, category: "Main Course", type: 'veg' },
  { id: 34, name: "Aloo Bhujia", price: 30, category: "Main Course", type: 'veg' },
  { id: 35, name: "Dal Fry", price: 40, category: "Main Course", type: 'veg' },
  { id: 36, name: "Dal Tadka", price: 40, category: "Main Course", type: 'veg' },
  { id: 37, name: "Plain Rice", price: 40, category: "Sides", type: 'veg' },
  { id: 38, name: "Roti (per pc)", price: 5, category: "Bread", type: 'veg' },
  { id: 39, name: "Plain Paratha", price: 15, category: "Bread", type: 'veg' },
  { id: 40, name: "Laccha Paratha", price: 25, category: "Bread", type: 'veg' },
  { id: 41, name: "Samosa", price: 10, category: "Snacks", type: 'veg' },
  { id: 42, name: "Aloo Chop", price: 10, category: "Snacks", type: 'veg' },
  { id: 43, name: "Bread Pakoda", price: 12, category: "Snacks", type: 'veg' },
  { id: 44, name: "Veg Roll", price: 40, category: "Rolls", type: 'veg' },
  { id: 45, name: "Egg Roll", price: 50, category: "Rolls", type: 'egg' },
  { id: 46, name: "Chicken Roll", price: 60, category: "Rolls", type: 'non-veg' },
  { id: 47, name: "Chicken Egg Roll", price: 70, category: "Rolls", type: 'non-veg' },
  { id: 48, name: "Veg Chowmein", price: 50, category: "Chinese", type: 'veg' },
  { id: 49, name: "Egg Chowmein", price: 60, category: "Chinese", type: 'egg' },
  { id: 50, name: "Chicken Chowmein", price: 70, category: "Chinese", type: 'non-veg' },
  { id: 51, name: "Veg Fried Rice", price: 50, category: "Chinese", type: 'veg' },
  { id: 52, name: "Egg Fried Rice", price: 60, category: "Chinese", type: 'egg' },
  { id: 53, name: "Chicken Fried Rice", price: 70, category: "Chinese", type: 'non-veg' },
  { id: 54, name: "Paneer Chilli (Amul Paneer)", price: 70, category: "Chinese", type: 'veg' },
  { id: 55, name: "Chicken Chilli", price: 80, category: "Chinese", type: 'non-veg' },
  { id: 56, name: "Veg Manchurian", price: 60, category: "Chinese", type: 'veg' },
  { id: 57, name: "Veg Soup", price: 40, category: "Soup", type: 'veg' },
  { id: 58, name: "Chicken Soup", price: 50, category: "Soup", type: 'non-veg' },
  { id: 59, name: "Mutton Biryani", price: 140, category: "Biryani", isFamous: true, type: 'non-veg' },
];
